# Generated by Django 4.1 on 2022-09-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firebase_id",
            new_name="firebase_uid",
        ),
    ]
