# Generated by Django 4.0.1 on 2023-01-31 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='INVALID@INVALID.COM', max_length=320, unique=True, validators=[django.core.validators.MaxLengthValidator(320)]),
            preserve_default=False,
        ),
    ]
