# Generated by Django 4.0.1 on 2022-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_alias_user_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
