# Generated by Django 4.0.1 on 2022-12-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('expense_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='expenses.expense')),
                ('userToShareFlag', models.BooleanField(default=True)),
                ('userToShare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userToShare', to='users.user')),
            ],
            bases=('expenses.expense',),
        ),
    ]
