# Generated by Django 4.0.1 on 2022-12-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedExpenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedexpense',
            name='aceptedTransaction',
            field=models.BooleanField(default=False),
        ),
    ]
