# Generated by Django 4.0.1 on 2023-01-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='future_expense',
            field=models.BooleanField(default=False),
        ),
    ]
