# Generated by Django 4.0.1 on 2022-10-08 18:51

import django.core.validators
from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=11, validators=[django.core.validators.MinValueValidator(0.01), expenses.models.validate_date_is_not_in_the_future]),
        ),
    ]
