# Generated by Django 4.0.1 on 2022-12-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense',
            field=models.BooleanField(default=True),
        ),
    ]
