# Generated by Django 4.0.1 on 2022-12-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.CharField(default='true', max_length=5),
        ),
    ]
