# Generated by Django 4.0.1 on 2022-12-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_color'),
        ('expenses', '0003_alter_expense_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.BooleanField(default=True),
        ),
    ]
