# Generated by Django 4.0.1 on 2022-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expense_category_alter_expense_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='isExpense',
            field=models.BooleanField(default=True),
        ),
    ]
