# Generated by Django 4.0.1 on 2022-12-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_remove_expense_expense_expense_isexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='isExpense',
            new_name='expense',
        ),
    ]
