# Generated by Django 4.0.1 on 2022-12-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense',
            field=models.BooleanField(default=True),
        ),
    ]
