# Generated by Django 4.0.1 on 2022-12-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expense_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
