# Generated by Django 4.1 on 2022-09-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=11),
        ),
    ]
