# Generated by Django 4.0.1 on 2022-10-15 21:46

from django.db import migrations, models

def update_categories_color(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')

    colors = {
        1: "rgba(255,255,255,0.2)",
        2: "rgba(0,255,0,0.2)",
        3: "rgba(0,255,124,0.2)",
        4: "rgba(255,0,0,0.2)",
        5: "rgba(255,0,255,0.2)"
    }

    for category_id in range(1, 6):
        category = Category.objects.get(id=category_id)
        category.color = colors[category_id]
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.RunPython(update_categories_color)
    ]
