# Generated by Django 4.0.1 on 2022-10-15 21:46

from django.db import migrations, models

from utils import create_random_color_string

def update_categories_color(apps, schema_editor):
    Category = apps.get_model('categories', 'Category')

    colors = {
        1: "rgba(0,255,255,1)",
        2: "rgba(0,255,0,1)",
        3: "rgba(0,255,124,1)",
        4: "rgba(255,0,0,1)",
        5: "rgba(255,0,255,1)",
        6: "rgba(255,0,199,1)"
    }

    for category in Category.objects.all():
        if category.color is None:
            if category.id in colors:
                category = Category.objects.get(id=category.id)
                category.color = colors[category.id]
            else:
                category.color = create_random_color_string()

        category.save()



class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default=None, editable=False, max_length=50, null=True),
        ),
        migrations.RunPython(update_categories_color)
    ]
