# Generated by Django 4.0.1 on 2022-12-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shareExpense',
        ),
    ]
