# Generated by Django 4.0.1 on 2022-12-02 00:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_color'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureExpenseDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0.01, max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('name', models.CharField(max_length=50, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('assigned_budget', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budget')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='LimitDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, default=0.01, max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('assigned_budget', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.budget')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddConstraint(
            model_name='limitdetail',
            constraint=models.UniqueConstraint(fields=('assigned_budget', 'category'), name='category repetition in limit detail is not allowed'),
        ),
        migrations.AddConstraint(
            model_name='futureexpensedetail',
            constraint=models.UniqueConstraint(fields=('assigned_budget', 'category'), name='category repetition in future expense detail is not allowed'),
        ),
    ]
