# Generated by Django 4.0.1 on 2023-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_futureexpensedetail_limitdetail_delete_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futureexpensedetail',
            name='expended',
            field=models.BooleanField(default=False),
        ),
    ]
