# Generated by Django 4.0.1 on 2023-01-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_futureexpensedetail_expended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='final_date',
            field=models.DateField(),
        ),
    ]
