# Generated by Django 4.0.1 on 2023-01-30 21:12

import budgets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_budget_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='final_date',
            field=models.DateField(validators=[budgets.models.validate_date_is_not_in_the_past]),
        ),
    ]
